#!/usr/bin/env bash

echo "======= SAVE YOUR NOTEBOOK (then press 'return') =========="
read

cp Assignment.ipynb Assignment.backup.ipynb
git commit -am "My progress so far."
git pull --no-edit upstream main -X ours
